# this is a file to collect the data to be used

dish_type = ["stir-fry", "cake", "salad", "sandwich", "soup", "noodles"]

adjectives = ["delicious", "healthy", "colorful", "glamorous", "addictive", "tasty", "obnoxious", "fabulous", "beautiful", "popular", "quality", "amazing"]

animal_meats = [
    "american bison",
    "water buffalo",
    "cattle",
    "yak",
    "dromedary",
    "llama",
    "dog",
    "goat",
    "elk",
    "fallow deer",
    "moose",
    "red deer",
    "reindeer",
    "white-tailed deer",
    "donkey",
    "horse",
    "rabbit",
    "kangaroo",
    "sheep",
    "guinea pig",
    "rat",
    "pig",
    "wild boar",
    "frogs",
    "chicken",
    "duck",
    "goose",
    "turkey",
    "quail",
    "pigeon",
    "guineafowl",
    "ostrich",
    "emu",
    "peacocks",
    "barramundi",
    "carp",
    "catfish",
    "cod",
    "common seabream",
    "dentex",
    "flounder",
    "gilthead seabream",
    "halibut",
    "meagre",
    "milkfish",
    "rabbitfish",
    "salmon",
    "seabass",
    "sharpsnout seabream",
    "striped bass",
    "sturgeon",
    "tilapia",
    "trout",
    "turbot",
    "wuchang bream",
    "cricket",
    "grasshopper",
    "maguey worm",
    "mopane worm",
    "silkworm",
    "crayfish",
    "crab",
    "lobster",
    "shrimp",
    "prawns",
    "oysters",
    "scallop",
    "mussels",
    "land snails",
    "abalone",
    "alligator",
    "crocodile",
    "turtle",
    "snake",
    "iguana",
    "whale",
    "dolphin"
]

grains = [
    "finger millet",
    "fonio",
    "foxtail millet",
    "Japanese millet",
    "Job's tears",
    "kodo millet",
    "corn",
    "millet",
    "pearl millet",
    "proso millet",
    "sorghum",
    "barley",
    "oats",
    "rice",
    "rye",
    "spelt",
    "teff",
    "triticale",
    "wheat",
    "wild rice",
    "amaranth",
    "buckwheat",
    "chia",
    "quinoa",
    "kañiwa",
    "chickpeas",
    "common beans",
    "garden peas",
    "fava beans",
    "lentils",
    "lima beans",
    "lupins",
    "mung beans",
    "peanuts",
    "pigeon peas",
    "runner beans",
    "soybeans",
    "black mustard",
    "India mustard",
    "rapeseed",
    "safflower",
    "sunflower seed",
    "flax seed",
    "hemp seed",
    "poppy seed"
]

leaf_veggies = [
    "arugula",
    "beet greens",
    "bok choy",
    "broccoli leaves",
    "brussels sprouts",
    "cabbage",
    "celery",
    "chinese cabbage",
    "collard greens",
    "corn salad",
    "cress",
    "dandelion",
    "endive",
    "fiddlehead",
    "kale",
    "kalette",
    "komatsuna",
    "lamb's lettuce",
    "lettuce",
    "malabar spinach",
    "miner's lettuce",
    "mizuna greens",
    "mustard greens",
    "napa cabbage",
    "new zealand spinach",
    "pak choy",
    "paracress",
    "pea leaves",
    "radicchio",
    "rapini (broccoli rabe)",
    "red spinach",
    "samphire",
    "sea kale",
    "shepherd's purse",
    "soko",
    "sorrel",
    "spinach",
    "swiss chard",
    "tatsoi",
    "turnip greens",
    "vegetable fern",
    "watercress",
    "water spinach",
    "wheatgrass",
    "yarrow",
    "yao choy",
    "catsear",
    "chickweed"
]

fruits = [
    "apple",
    "apricot",
    "avocado",
    "banana",
    "blackberry",
    "blueberry",
    "cherry",
    "coconut",
    "cranberry",
    "cucumber",
    "date",
    "dragonfruit (pitaya)",
    "durian",
    "elderberry",
    "fig",
    "grape",
    "grapefruit",
    "guava",
    "jackfruit",
    "kiwi",
    "lemon",
    "lime",
    "lychee",
    "mango",
    "mangosteen",
    "melon",
    "cantaloupe",
    "honeydew",
    "watermelon",
    "nectarine",
    "orange",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "pineapple",
    "plum",
    "pomegranate",
    "raspberry",
    "strawberry",
    "tangerine",
    "tomatillo",
    "tomato",
    "watermelon",
    "jackfruit",
    "lychee",
    "rambutan",
    "kumquat",
    "guava",
    "persimmon",
    "carrot",
    "potato",
    "tamarind"
]


# this one I came up with myself - the reason why it is significantly shorter
seasoning = [
    "salt",
    "pepper",
    "sugar",
    "garlic powder",
    "turmeric powder",
    "chilli flakes",
    "chicken bouillion",
    "worcestershire sauce",
    "ketchup",
    "mayonnaise",
    "mustard",
    "sichuan peppercorns",
    "soy sauce",
    "fish sauce",
    "curry powder",
    "stevia",
    "sesame oil",
    "wasabi",
    "cinnamon",
    "marmite",
    "vegemite"
]

nuts = [
    "acorn",
    "almond",
    "beech",
    "brazil nut",
    "candlenut",
    "cashew",
    "chestnut",
    "chinquapin",
    "coconut",
    "coquito",
    "dika",
    "ginkgo",
    "hazelnut",
    "hickory",
    "kola nut",
    "macadamia",
    "malabar chestnut",
    "mongongo",
    "ogbono",
    "pachira",
    "paradise nut",
    "peanut",
    "pequi",
    "pili nut",
    "pine nut",
    "pistachio",
    "sapucaia",
    "soybean",
    "sunflower seed",
    "tiger nut",
    "walnut"
]
