# this is a file to collect the data to be used

dish_type = ["savory", "light", "dessert"]

animal_meats = [
    "american bison",
    "water buffalo",
    "cattle",
    "domestic yak",
    "dromedary",
    "llama",
    "dog",
    "domestic goat",
    "elk",
    "fallow deer",
    "moose",
    "red deer",
    "reindeer",
    "white-tailed deer",
    "donkey",
    "horse",
    "rabbit",
    "kangaroo",
    "domestic sheep",
    "guinea pig",
    "rat",
    "pig",
    "wild boar",
    "frogs",
    "chicken",
    "duck",
    "goose",
    "turkey",
    "quail",
    "pigeon",
    "guineafowl",
    "ostrich",
    "emu",
    "peacocks",
    "barramundi",
    "carp",
    "catfish",
    "cod",
    "common seabream",
    "dentex",
    "flounder",
    "gilthead seabream",
    "halibut",
    "meagre",
    "milkfish",
    "rabbitfish",
    "salmon",
    "seabass",
    "sharpsnout seabream",
    "striped bass",
    "sturgeon",
    "tilapia",
    "trout",
    "turbot",
    "wuchang bream",
    "cricket",
    "grasshopper",
    "maguey worm",
    "mopane worm",
    "silkworm",
    "crayfish",
    "crab",
    "lobster",
    "shrimp",
    "prawns",
    "oysters",
    "scallop",
    "mussels",
    "land snails",
    "abalone",
    "alligator",
    "crocodile",
    "turtle",
    "snake",
    "iguana",
    "whale",
    "dolphin"
]

grains = [
    "finger millet",
    "fonio",
    "foxtail millet",
    "Japanese millet",
    "Job's tears",
    "kodo millet",
    "corn",
    "millet",
    "pearl millet",
    "proso millet",
    "sorghum",
    "barley",
    "oats",
    "rice",
    "rye",
    "spelt",
    "teff",
    "triticale",
    "wheat",
    "wild rice",
    "amaranth",
    "buckwheat",
    "chia",
    "quinoa",
    "kañiwa",
    "chickpeas",
    "common beans",
    "garden peas",
    "fava beans",
    "lentils",
    "lima beans",
    "lupins",
    "mung beans",
    "peanuts",
    "pigeon peas",
    "runner beans",
    "soybeans",
    "black mustard",
    "India mustard",
    "rapeseed",
    "safflower",
    "sunflower seed",
    "flax seed",
    "hemp seed",
    "poppy seed"
]

leaf_veggies = [
    "Arugula",
    "Beet greens",
    "Bok choy",
    "Broccoli leaves",
    "Brussels sprouts",
    "Cabbage",
    "Celery",
    "Chinese Cabbage",
    "Collard greens",
    "Corn salad",
    "Cress",
    "Dandelion",
    "Endive",
    "Fiddlehead",
    "Kale",
    "Kalette",
    "Komatsuna",
    "Lamb's lettuce",
    "Lettuce",
    "Malabar spinach",
    "Miner's lettuce",
    "Mizuna greens",
    "Mustard greens",
    "Napa cabbage",
    "New Zealand Spinach",
    "Pak choy",
    "Paracress",
    "Pea leaves",
    "Radicchio",
    "Rapini (broccoli rabe)",
    "Red spinach",
    "Samphire",
    "Sea kale",
    "Shepherd's purse",
    "Soko",
    "Sorrel",
    "Spinach",
    "Swiss chard",
    "Tatsoi",
    "Turnip greens",
    "Vegetable fern",
    "Watercress",
    "Water spinach",
    "Wheatgrass",
    "Yarrow",
    "Yao choy",
    "Catsear",
    "Chickweed",
    "Garland Chrysanthemum",
    "Greater plantain"
]

fruits = [
    "Abiu",
    "Açaí",
    "Acerola",
    "Ackee",
    "African Cherry Orange",
    "Akebi",
    "Amla (Indian Gooseberry)",
    "Apple",
    "Apricot",
    "American Mayapple",
    "Aratiles",
    "Araza",
    "Atis (Annona Squamosa)",
    "Avocado",
    "Banana",
    "Barberry",
    "Bell pepper",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Buddha’s hand (fingered citron)",
    "Cacao",
    "Cactus pear",
    "Calamondin (Calamansi)",
    "Canistel (egg fruit)",
    "Cape Gooseberry (Physalis)",
    "Carolina reaper",
    "Catmon",
    "Cempedak",
    "Cherimoya",
    "Cherimoya (Custard Apple)",
    "Cherry",
    "Chico fruit",
    "Chile pepper",
    "Cloudberry",
    "Coco de mer",
    "Coconut",
    "Corn kernel",
    "Crab apple",
    "Cranberry",
    "Crowberry",
    "Cucumber",
    "Currant",
    "Custard Apple",
    "Date",
    "Date Plum",
    "Dragonfruit (Pitaya)",
    "Durian",
    "Eggplant (Brinjal)",
    "Elderberry",
    "Feijoa",
    "Feijoa (Pineapple Guava)",
    "Fig",
    "Finger Lime (Caviar Lime)",
    "Gac Fruit (Baby Jackfruit)",
    "Goji berry",
    "Goji Berry (Wolfberry)",
    "Goldenberry",
    "Gooseberry",
    "Grape",
    "Grapefruit",
    "Grewia asiatica (phalsa or falsa)",
    "Guarana",
    "Guava",
    "Guyabano",
    "Hala Fruit",
    "Hawthorn Berry",
    "Honeyberry",
    "Honeyberry (Haskap)",
    "Horned Melon (Kiwano)",
    "Huckleberry",
    "Indian Fig (Prickly Pear)",
    "Jaboticaba",
    "Jabuticaba (Plinia)",
    "Jackfruit",
    "Jalapeño",
    "Jambul",
    "Jambolan (Java Plum)",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Jujube (Red Date)",
    "Juniper berry",
    "Kaffir Lime",
    "Kaki (Persimmon)",
    "Kei Apple",
    "Kiwano (horned melon)",
    "Kiwifruit",
    "Kumquat",
    "Lanzones",
    "Lemon",
    "Lime",
    "Lingonberry",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lucuma",
    "Lulo",
    "Lychee",
    "Macopa (Wax Apple)",
    "Magellan Barberry",
    "Mamey Apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Maracuja (Passion Fruit)",
    "Marionberry",
    "Maqui Berry",
    "Medlar",
    "Melon",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Musk melon",
    "Watermelon",
    "Miracle fruit",
    "Momordica fruit",
    "Monstera deliciosa",
    "Morello Cherry",
    "Mulberry",
    "Nance",
    "Naranjilla (Lulo)",
    "Nectarine",
    "Noni",
    "Orange",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Pepino",
    "Persimmon",
    "Physalis (Ground Cherry)",
    "Pineapple",
    "Pineberry",
    "Pitanga (Surinam Cherry)",
    "Plantain",
    "Plum",
    "Plumcot (Pluot)",
    "Pomegranate",
    "Pomelo",
    "Pummelo",
    "Purple mangosteen",
    "Quince",
    "Raisin",
    "Rambutan (Mamin Chino)",
    "Raspberry",
    "Red Medlar",
    "Red Currant",
    "Redcurrant",
    "Rose apple",
    "Rose Hip",
    "Rowan Berry",
    "Salak (Snake Fruit)",
    "Salal berry",
    "Salmonberry",
    "Sampaloc",
    "Santol",
    "Sapodilla",
    "Sapote",
    "Sarguelas (Red Mombin)",
    "Satsuma",
    "Saquico",
    "Sea Buckthorn",
    "Serviceberry",
    "Sloe (Blackthorn)",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Sugar Apple (Sweetsop)",
    "Surinam cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Tambis (Water Apple)",
    "Thimbleberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Ximenia",
    "Yumberry",
    "Yuzu",
    "Carrot",
    "Potato"
]

# this one I came up with myself - the reason why it is significantly shorter
seasoning = [
    "salt",
    "pepper",
    "sugar",
    "garlic powder",
    "turmeric powder",
    "chilli flakes",
    "chicken bouillion",
    "worcestershire sauce",
    "ketchup",
    "mayonnaise",
    "mustard",
    "sichuan peppercorns",
    "soy sauce",
    "fish sauce",
    "curry powder",
    "stevia",
    "sesame oil",
    "wasabi",
    "cinnamon",
    "marmite",
    "vegemite"
]

nuts = [
    "Acorn",
    "Almond",
    "Beech",
    "Brazil nut",
    "Candlenut",
    "Cashew",
    "Chestnut",
    "Chinquapin",
    "Coconut",
    "Coquito",
    "Dika",
    "Ginkgo",
    "Hazelnut",
    "Hickory",
    "Kola nut",
    "Macadamia",
    "Malabar chestnut",
    "Mongongo",
    "Ogbono",
    "Pachira",
    "Paradise nut",
    "Peanut",
    "Pequi",
    "Pili nut",
    "Pine nut",
    "Pistachio",
    "Sapucaia",
    "Soybean",
    "Sunflower seed",
    "Tiger nut",
    "Walnut"
]